on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Setup .NET Core
    - uses: actions/setup-dotnet@v1
      name: .NET Core Build & Deployment
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release
    ‐ uses: docker/build-push-action@v1
      name: build-push
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        registry: docker.io
        repository: kamya24/kam1
        tags: v1
   
